// Widths generated for each photo (see scripts/optimize-images.mjs).
import manifest from "./image-manifest.json";

// Web-sized photos generated by `npm run images` into public/images.
// Each entry maps a readable name to the slug the script produced.
const photos = {
  teamWall: "business-team-planning-strategy-using-sticky-notes",
  teamTable: "collaborative-colleagues-discuss-sustainable-energ",
  eyes: "close-up-of-a-woman-s-face-and-eyes",
  glasses: "close-up-of-face-wearing-framed-glasses",
  portraitCalm: "close-up-of-woman-with-dark-hair",
  scissors: "creative-mind-cuts-photo-with-scissors-at-desk",
  scooter: "happy-couple-ride-along-city-street-on-scooter",
  officeMeeting: "office-colleagues-meeting-at-table-indoors",
  blueProfile: "pexels-cottonbro-6616605",
  goldenPortrait: "pexels-joshuaabner-5379788",
  profileSkin: "pexels-kpx-visuals-2156602524-36307503",
  workshop: "pexels-mikhail-nilov-9301252",
  braids: "pexels-oluseyi-18466015",
  glassSmile: "smiling-woman-in-plaid-shirt-behind-glass",
  headphones: "smiling-woman-with-afro-hair-and-headphones-leanin",
  clay: "smiling-young-woman-working-with-clay-at-studio",
  laptopMeeting: "team-meeting-collaboration-in-a-modern-office",
  conversation: "two-friends-enjoying-conversation-in-urban-setting",
} as const;

export type PhotoName = keyof typeof photos;

/*
  `sizes` hints for images that fill (object-fit: cover) a box taller than
  the photo's ~3:2 shape. The browser only knows the box width, so without
  this a full-height panel on a portrait phone downloads a file ~1.5x too
  small and looks soft on retina screens.
*/
export const coverSizes = "(max-aspect-ratio: 1/1) 150vh, 100vw";

export function photo(name: PhotoName) {
  const slug = photos[name];
  const widths: number[] = (manifest as Record<string, number[]>)[slug] ?? [640, 1280];
  return {
    src: `/images/${slug}-${widths.includes(1280) ? 1280 : widths[widths.length - 1]}.webp`,
    srcSet: widths.map((w) => `/images/${slug}-${w}.webp ${w}w`).join(", "),
  };
}
